### ISSUE TITLE
Feature Request:  Option (text,regex) to filter lookup results for editing

### ISSUE THREAD

**Issue by kyaparla** [LukeMurphey/lookup-editor#10]
Felt, its better to have a text field which can take text or regex to filter rows from lookup (csv or kvstore) for easy editing.

**Comment by LukeMurphey** [comment]
See related ticket: https://lukemurphey.net/issues/1081

**Comment by LukeMurphey** [comment]
This is now supported. It will be released in the next minor release version (3.4).
