### ISSUE TITLE
Feature Request (Lazy): Add "Open in Search" button inside of "Lookup Edit" page 

### ISSUE THREAD

**Issue by jdeer0618** [LukeMurphey/lookup-editor#16]
Luke, I'd like to make a super lazy request. Please add an "Open in Search" button on the "Lookup Edit" page.

![image](https://user-images.githubusercontent.com/4651176/31091854-fab64886-a771-11e7-920d-552f403f88b3.png)

Thanks!

JD

**Comment by LukeMurphey** [comment]
Definitely. I'm working on a new version of the Lookup Editor so I'll add this too.

**Comment by jdeer0618** [comment]
Thanks!

**Comment by jdeer0618** [comment]
Makes me wish I'd have found you at .conf and bought you a beer.

**Comment by LukeMurphey** [comment]
This was implemented in 3.0. See https://lukemurphey.net/issues/2082

I'll almost certainly be going to .conf again this year. I don't drink though :)
