### ISSUE TITLE
Time changes to epoch

### ISSUE THREAD

**Issue by Zeinstein** [LukeMurphey/lookup-editor#19]
Somehow the time picker changes to epoch when it appears on the lookup editor. Is it possible to reformat this to a human readable time?

**Comment by LukeMurphey** [comment]
What time are you referring to? Are you referring to the list of backups?

**Comment by Zeinstein** [comment]
The _time field is outputlookup in the format say %D, but when I load the lookup using lookup editor, it appears as epoch time. Why does the lookup editor load the _time field as epoch time when using | inputlookup lookuptable.csv shows the _time field as %D?

**Comment by Zeinstein** [comment]
![image](https://user-images.githubusercontent.com/235067/32375232-26608ad0-c0a1-11e7-97ab-437324f4b46c.png)
I mean this. (Upper one is the simple "inputlookup solution, lower one is lookup_editor).

**Comment by Zeinstein** [comment]
Oh, I've just figured it out. Our version was using an older lookup-editor...

**Comment by LukeMurphey** [comment]
Yeah, that makes sense. I'll plan on implementing _time human readable.

**Comment by LukeMurphey** [comment]
This was implemented in 3.0. See https://lukemurphey.net/issues/2129
