### ISSUE TITLE
Splunk showing gateway timeout

### ISSUE THREAD

**Issue by gnanasekar6914** [LukeMurphey/lookup-editor#21]
We're running Splunk in our environment. We can only access the Splunk instance via the IP address, but not the DNS address we have mapped to it.

For instance, we can go to this URL using the IP:

http://10.40.50.17:8000/en-US/app/launcher/home

Splunk is working fine. However if I go to:

http://splunk.mycompany.com:8000/en-US/app/launcher/home | [Splunk Security](https://mindmajix.com/splunk-training)

**I get a gateway timeout error:**

Gateway Timeout
Server error - server 10.40.50.17 is unreachable at this moment.
Please retry the request or contact your adminstrator.

I'm wondering where the issue may lie. Is this a problem with Splunk? Do I need to make Splunk aware of the DNS address that I'm giving it?

Help me on this.

**Comment by LukeMurphey** [comment]
This isn't an issue with the Lookup Editor but rather something with your Splunk setup. I recommend talking to Support.
