### ISSUE TITLE
compatible with Splunk 7.x?

### ISSUE THREAD

**Issue by tmartin14** [LukeMurphey/lookup-editor#22]
Attempting to use this with a 7.0 version of Splunk, but it no longer seems to work.  Any attempt to view or edit a lookup results in an error message showing "This lookup file could not be found".  

![screen shot 2018-01-19 at 12 27 14 pm](https://user-images.githubusercontent.com/1749572/35164734-9bd44f7c-fd19-11e7-8fba-ac0f0bdd162c.png)

**Comment by LukeMurphey** [comment]
I'm using it on Splunk 7.0 and it is working for me. Did anything recently change to cause the app to change behavior (like upgrading Splunk, upgrading the Lookup Editor app, etc.)?

**Comment by tmartin14** [comment]
Must have been bad data in the csv.   I reloaded the .csv file with an updated version and everything is working as expected now.   Sorry for the noise, but Thanks for the reply!
