### ISSUE TITLE
Lookup editor only shows _key field from kvstore

### ISSUE THREAD

**Issue by hegga** [LukeMurphey/lookup-editor#24]
Hi.

We are experiencing some issues with the Lookup editor app and KV store data. For some of the kvstores only the field _key is shown in Lookup editor whilst the kvstore contains other data.

I've attached two images showing both how the kvstore looks in Lookup editor, and that the kvstore contains other fields as well using inputlookup.

This kvstore in question belongs to the TA_linux auditd app in case that is of interest.

![kvstore-error1](https://user-images.githubusercontent.com/49037/39400083-ccdf8bdc-4b29-11e8-99c6-08d37bf4966c.png)
![kvstore-inputlookup](https://user-images.githubusercontent.com/49037/39400087-d1ce6744-4b29-11e8-8fa3-587532fa73f5.PNG)

transforms.conf:
[auditd_host_inventory]
external_type = kvstore
collection = auditd_host_inventory
fields_list = _key, kernel_version, distribution_release, architecture 

collections.conf:
[auditd_host_inventory]
replicate = true

Any ideas on how we can go about solving this issue?

Best regards,

Helge Aksdal

**Comment by LukeMurphey** [comment]
I have a repro on this. Thanks for the very clear description. I'm trying to diagnose why this isn't working.

**Comment by LukeMurphey** [comment]
This is occurring because the Lookup Editor assumes that the fields ought to specified in collections.conf. However, the fields are listed in transforms.conf in this case. The app now loads the fields from transforms.conf if they aren't found in collections.conf.

**Comment by LukeMurphey** [comment]
By the way: my plan is to ship this fix in the next maintenance release: 3.0.2.

**Comment by hegga** [comment]
Awesome! Thanks Luke, both for fixing this bug, and for the awesome Splunk app!
