### ISSUE TITLE
field types for kvstore lookups

### ISSUE THREAD

**Issue by MattUebel** [LukeMurphey/lookup-editor#26]
the lookup editor doesn't give any guidance on the field types, which makes it difficult to edit a lookup that has multiple types (string, time, bool, number)

When opening a kvstore lookup with a bool field for the first time, it has a strange set of characters for the bool column that all resolve to checkboxes when any of them are clicked.

A stronger indication of the expected data format for each column would help

**Comment by LukeMurphey** [comment]
This is way better now. I replaced the handsontable with another library that handles those booleans better. Array values and dates are handled elegantly too.
