### ISSUE TITLE
Unable to view/edit lookups on SHC with SSO/SAML (Okta) enabled

### ISSUE THREAD

**Issue by yorokobi** [LukeMurphey/lookup-editor#27]
Splunk Enterprise 6.5.6
Lookup Editor 3.0.0 (same with 2.7)

I deployed the Lookup Editor app as-is via the SHC Deployer but every time I (as an admin) or any other user goes to the app (`/en-US/app/lookup_editor/`) and tries to view/edit a lookup (CSV or KV store), the app returns the following error:

    The requested lookup file does not exist
I have tweaked lookup permissions (global, Everyone read/write, etc.) to no avail and added

    [global]
    allowRestReplay = true
as well as manually restarted Splunk on each SHC member (except the Deployer).

If I bypass SSO (`/en-US/account/login?loginType=splunk`) and log in as the admin user, the app works as expected.

No logs are generated when attempting to use the app when signed in via SSO/SAML.

Health status shows `Online` for both "Lookup Editor REST handler" and "Lookup Backups REST Handler". Logs are generated when I perform an action when bypassing SSO and logging in as admin.

**Comment by LukeMurphey** [comment]
This should be fixed now. I fixed a couple of issues related to username handling in 3.0.3.
