### ISSUE TITLE
Editing a lookup with an _time field stored as epoch breaks things

### ISSUE THREAD

**Issue by mew1033** [LukeMurphey/lookup-editor#28]
I have a csv lookup that looks something like this:

    Group,"Total Widgets","_time","_timediff",count
    Group1,47484,1526616000,,88
    "Group2 - Awesome",4370,1526616000,,67
    Group3,593,1526616000,,14
    Group4,151,1526616000,,217
    Group5,1553,1526616000,,0
    Group16,361,1526616000,,195

When I open the lookup in the lookup editor, the _time field is human readable. Okay, that's fine. It's nice to see an easier to read time. But if I edit anything and save the lookup, all the _time fields get replaced with `NaN`, which is a Very Bad Thing™. Is there a setting I missed to have that not happen? Or maybe this is a bug in the lookup editor?

**Comment by LukeMurphey** [comment]
I have confirmed this as a bug and I have a fix in place. This will be released in version 3.0.3.

**Comment by MattUebel** [comment]
Great, thanks!

**Comment by LukeMurphey** [comment]
3.0.3 was just released.
