### ISSUE TITLE
KVStore Not Found

### ISSUE THREAD

**Issue by boojew** [LukeMurphey/lookup-editor#29]
Using 3.0.3, when trying to open an existing KVStore, I get "The requested lookup file does not exist". I see the same error after creating a new kvstore both in the app and outside. I could not find any logs to share. This in a SHC environment

**Comment by boojew** [comment]
Nevermind.. I needed to restart my SHC

**Comment by boojew** [comment]
Actually, it seems to be coming back intermittently. All nodes of my SHC have been restarted since installing the app. The issue also seems to exist for CSVs.

**Comment by LukeMurphey** [comment]
Can you look into the browser console logs and see if there are any calls that fail?

**Comment by boojew** [comment]
Yea, I'm getting https://<redacted>/en-US/custom/lookup_editor/lookup_edit/get_lookup_contents?lookup_file=test2&namespace=search&header_only=false&lookup_type=kv&owner=nobody&_=1528294650964

**Comment by LukeMurphey** [comment]
My guess is that this is some install problem with SHC. You may want to try restarting the SHC again. I have seen cases in the past where I debugged a customer's environment for SHC issues related to an app only to have the issue go away when the customer decided to restart the search heads as a last attempt.

My guess is that there is some sort of race condition that causes some search heads to not pick up the changes.

**Comment by boojew** [comment]
Sorry - seems like it ended up being a browser issue. Clearing cache fixed the issue. Sorry about that

**Comment by qn7o** [comment]
Just FYI, same thing for me with version 3.0.4: a browser cache clear (CTRL+Shift+R in Chrome, for instance) is necessary to make the "The requested lookup file does not exist" error go away.
