### ISSUE TITLE
Quote all empty (or all) fields

### ISSUE THREAD

**Issue by baldwintm** [LukeMurphey/lookup-editor#3]
I have a need to have empty strings enclosed in double-quotes.

If a field is empty in the lookup table, I would like the CSV file to contain an empty quoted string (,"",).
One way would be to implement that logic manually in your script. 

Another way would be to have an option to have all fields quoted. (possibly as a checkbox on the lookup_edit view, or as a global option for all lookups)
This option would just need to modify line #410 in [lookup_edit.py](https://github.com/LukeMurphey/lookup-editor/blob/master/src/appserver/controllers/lookup_edit.py#L410)  to pass "```quoting=csv.QUOTE_ALL```" or "```quoting=csv.QUOTE_NONNUMERIC```" to the csv.writer call.

let me know if there are any questions about this feature request

**Comment by LukeMurphey** [comment]
Could you clarify why you would prefer empty quoted strings? I'm not questioning if there is a good reason, it just isn't clear to me why that would be preferred.

**Comment by baldwintm** [comment]
I have worked around this problem at this time's

I was trying to get Splunk to match on an empty field in a column, but it
would only work if I had an empty quoted string.

I worked around this by just making that column a wildcard column.
I had to change the logic of the search a little bit, but I'm okay with how
it turned out.

Thank you,
Tim Baldwin
