### ISSUE TITLE
Fields with spaces require doublequotes when added to transforms.conf

### ISSUE THREAD

**Issue by hortonew** [LukeMurphey/lookup-editor#30]
When creating the transforms.conf entry for kvstore lookup today (latest version), fieldnames with spaces need to be added with double quotes around them in the transforms.conf entry.  Otherwise, only ones without spaces will show up when doing |inputlookup .

**Comment by hortonew** [comment]
Simple enough to just always put double quotes around all fields going to transforms.conf supported fields.

**Comment by LukeMurphey** [comment]
Good catch. This is fixed and the fix is about to be released in 3.0.4. Reference https://lukemurphey.net/issues/2272
