### ISSUE TITLE
Cannot Create Lookup From Lookup Editor

### ISSUE THREAD

**Issue by jwilczek** [LukeMurphey/lookup-editor#34]
I am using Splunk 7.2.0 and cannot create a lookup (CSV or KV) with the lookup editor app. When clicking "Create a New Lookup" I am redirected to a blank page.

![image](https://user-images.githubusercontent.com/8474603/48984099-0a793180-f0bd-11e8-96c2-996cbaf7ac4c.png)
 
Seeing that 3.0.5 was relatively new, I tried 3.04 and 3.05 and see the same issue with both versions.

**Comment by jwilczek** [comment]
I can provide the logs when I get home this afternoon.

Roger, I know I can create lookups the traditional way and have done so. However, lookups created this way are not visible by the Lookup Editor app. I'm running the free version of Splunk (500 MB/day) where you are only allowed one account, admin. I'm wondering if there's a permissions issue somewhere?

I'll provide logs in a few hours.

**Comment by jwilczek** [comment]
Was the log helpful?

**Comment by LukeMurphey** [comment]
I see what is going on . I ought to be able to fix this such that the page works with the free licence. I have this slated for the next maintenance release.

**Comment by jwilczek** [comment]
Could you provide guidance so I can make the change locally to test?

**Comment by LukeMurphey** [comment]
I'll provide a pre-release build so that you can test it. I'm pretty sure I can reproduce the issue locally though using the free license. If I can reliably reproduce it, I can reliably fix it.

**Comment by jwilczek** [comment]
Sure,  let me know if you need any additional information.

**Comment by LukeMurphey** [comment]
3.3.2 includes a fix for this.

**Comment by jwilczek** [comment]
I am still seeing issues  with lookups created the traditional way - I cannot see them in the Lookup Editor app.
