### ISSUE TITLE
Numbers truncate oddly on display through the UI

### ISSUE THREAD

**Issue by bcronrath** [LukeMurphey/lookup-editor#35]
For instance, if I input a number as "0.000000688", it will automatically convert it to 6.88e-7, which I suppose is fine, and this is how the actual value is stored, however the display through the ui after you refresh it is just -6.887  which is very misleading.  This is on the latest version available on splunk base 3.0.5

**Comment by LukeMurphey** [comment]
This behavior has been changed. The numbers no longer reformat like this. This change will be reflected in version 3.4 (will be released once I do more testing).
