### ISSUE TITLE
lookup_editor/appserver/static/js/utils/FormatTime.js should be formatTime.js

### ISSUE THREAD

**Issue by tkoeberl** [LukeMurphey/lookup-editor#42]
Same as described here: 
https://answers.splunk.com/answers/741202/lookup-editor-321-the-requested-lookup-file-does-n.html

**Comment by LukeMurphey** [comment]
This was fixed in version 3.3.1. You will likely need to clear your browser cache and/or bump Splunk to make sure that the changes show up in people's browsers.

See also: https://lukemurphey.net/issues/2389
