### ISSUE TITLE
bundle replication blacklist incomplete?

### ISSUE THREAD

**Issue by jksecurity** [LukeMurphey/lookup-editor#50]
Hi Luke,

Using the distsearch.conf you are preventing a SH from including the lookup_file_backups folder in the knowledge bundle. However, in our environment (pretty standard SHC) we seem to have the folder "lookup_file_backups.default" popping up, which does not match the bundle replication blacklist.

I am not sure whether this is specific to our environment or not. We are running Splunk 8.0.3 with backup replication enabled.

I have resolved this by changing distsearch.conf to:

    [replicationBlacklist]
    lookup_backups_blacklist_apps = apps/.../lookup_file_backups(.default)?/...
    lookup_backups_blacklist_users = users/.../lookup_file_backups(.default)?/...

Kr,

Jerome

**Comment by LukeMurphey** [comment]
Good catch. This has been fixed.
