### ISSUE TITLE
Last line is being deleted.

### ISSUE THREAD

**Issue by sfoster411** [LukeMurphey/lookup-editor#51]
The last line that is being added is not getting saved.  So if you only add one line it is not getting saved.

Thanks
Sean

**Comment by LukeMurphey** [comment]
Ok, it took me a while to build a reproduction of this bug but I figured it out. The editor seems not recognize newly entered values until the value is persisted into the table by clicking out of the cell you are editing.

I'm looking into solutions in https://lukemurphey.net/issues/2777

**Comment by LukeMurphey** [comment]
Fixed in version 3.4.2.
