### ISSUE TITLE
Create New Lookup > import file, only imports first 6 column

### ISSUE THREAD

**Issue by teunlaan** [LukeMurphey/lookup-editor#52]
When importing a tile with more than 6 columns, it only imports only de first 6.
When we first add more columns it imports the number of columns you created.

We experiance it with versions
3.4.1 and 3.4.2 (haven't tested other versions) All running on Splunk 7.3.5

**Comment by scoxspau** [comment]
I'm also seeing the same behaviour on 3.4.3 and Splunk Cloud 7.2.9

**Comment by LukeMurphey** [comment]
This is fixed in 3.4.5.
