### ISSUE TITLE
Save hangs in 3.4.2

### ISSUE THREAD

**Issue by afxmac** [LukeMurphey/lookup-editor#53]
Since Upgrading to 3.4.2 I can no longer save. 
Pressing the save button shows "saving..." but never returns.
No Errors in the logs

A downgrade to 3.4.1 fixed it for me.

This is on Splunk 7.2.4 on RJHEL7

**Comment by LukeMurphey** [comment]
I was able to identify the root cause of this. 3.4.3 has a fix for it. This is a client-side issue so you will need to make sure the JavaScript isn't being cached for it to work.
