### ISSUE TITLE
horizontal scroll bar is not visible  

### ISSUE THREAD

**Issue by josh12121984** [LukeMurphey/lookup-editor#54]
we are experiencing an issue on the editor that Unable to scroll to the right or columns are invisible.
tried to open editor on both chrome and IE. 
![image](https://user-images.githubusercontent.com/67262657/85267159-805c9f00-b492-11ea-8f42-48c0aea5c05f.png)

**Comment by LukeMurphey** [comment]
I have confirmed this. Looking into this.

**Comment by LukeMurphey** [comment]
Fixed this in 3.4.5.
