### ISSUE TITLE
Fixed in version 3.4.2.

### ISSUE THREAD

**Issue by JimJimlin** [LukeMurphey/lookup-editor#55]
I got same situation, but I already upgrade to version 3.4.4

Fixed in version 3.4.2.

_Originally posted by @LukeMurphey in https://github.com/LukeMurphey/lookup-editor/issues/51#issuecomment-641058538_

**Comment by LukeMurphey** [comment]
The changes are likely being cached by the browser. Try the solution here: https://community.splunk.com/t5/Archive/How-do-I-clear-the-cache-to-see-the-changes-after-updating-a/m-p/400434
