### ISSUE TITLE
Problems with 3.4.1 on Splunk Enterprise 8.0.3

### ISSUE THREAD

**Issue by tlcooperoh** [LukeMurphey/lookup-editor#56]
I'm also experiencing:  Horizontal scroll bar not visible, Tab no longer works, Import only imports first 6 columns.  In addition, we're seeing the values of one cell overlapping the following cell (no adjustment of the columns as before).  Also we are unable to use alt/enter in a cell to create MV text field (could do this in previous versions)  My question is..if we're running Splunk 8.0.3 can we delete Lookup Editor 3.4.1 and run an older version to eliminate these problems?

**Comment by LukeMurphey** [comment]
You can just reinstall an older version. You will need to [bump Splunk](https://bit.ly/ClearTheCache).
