### ISSUE TITLE
Null characters in lookup files not handled, throws error

### ISSUE THREAD

**Issue by Swordopolis** [LukeMurphey/lookup-editor#76]
Hi Luke,
 
It seems that if a lookup file contains a null character (displays as  "^@" in vim, for example), lookup-editor fails to read the file, and the user sees the following when trying to open the file in the UI:
`<yellow exclamation mark icon> This lookup could not be loaded from server`

Tracing the issue with search `index=_internal source="/opt/splunk/var/log/splunk/lookup_editor_rest_handler.log"`, I found the following error message:
```
ERROR Lookup file could not be loaded
Traceback (most recent call last):
  File "/opt/splunk/etc/apps/lookup_editor/bin/lookup_editor_rest_handler.py", line 138, in get_lookup_contents
    for row in csv_reader:
_csv.Error: line contains NUL
```

I was able to solve my issue by simply editing the file and removing the null characters, but it would be nice if lookup-editor could simply handle the nulls while parsing the file.

**Comment by gxgl** [comment]
Hi Luke, 

same issue here, unfortunately. We fixed in same way as @Swordopolis, but it will be good to have the fix from @bpatter5 in the next release on splunkbase.

Thank you for your work and support.

Best Regards,
George

**Comment by gxgl** [comment]
Hi! 

There is a new version (3.6.0) publihsed on Splunkbase on 5th of May 2022.
I have tested it with 101% Success!!!

Thanks to all that have added their contribution to fixing this and also to the Splunk team that pushed the code to prod :)

BR,
George
